### ISSUE TITLE
Windows10 32 bit and Windows 10 64 bit

### ISSUE THREAD

**Issue by dstyvsky** [slaeryan/FALCONSTRIKE#2]
just trying to pop calc
msfvenom -a x86 -p windows/exec cmd=calc.exe -b "\x00\x0a\x0d" -f hex > outfile
hosted raw on github
generate falconstrike executable and run and nothing happens

**Comment by slaeryan** [comment]
Hey mate!

Have you set the target hostname in the implant as the victim hostname?
And the killdate?
This is a targeted implant and it just won't execute if the conditions aren't correct.
I just tested it and it works fine!
Here is the shellcode I used:
https://raw.githubusercontent.com/slaeryan/DigitalOceanTest/master/calc_shellcode_32_hex.txt
Generated using:
 msfvenom -a x86 -p windows/exec cmd=calc.exe -f hex > outfile.txt
Note that you do not need to remove bad characters from the shellcode and this is an optional step but I don't see why that should create problems.
Also, for x86 shellcode you'd need to generate a 32-bit implant with the i686 build option.
I'd recommend you to read the blog post if you haven't already.
Cheers!

**Comment by dstyvsky** [comment]
[Videos.zip](https://github.com/slaeryan/FALCONSTRIKE/files/4600372/Videos.zip)

**Comment by dstyvsky** [comment]
I get a build warning


./source/injector.cpp: In function ‘void addressOfEntryPointInjection(unsigned char*, int)’:
./source/injector.cpp:46:42: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   46 |  ReadProcessMemory(pi.hProcess, (LPCVOID)pebOffset, &imageBase, 4, NULL);
      | 


But the executable is generated as shown in the videos.

**Comment by slaeryan** [comment]
Yes, you can ignore the build warnings for now. That won't be a problem and the FalconZero implant will still execute.

**Comment by dstyvsky** [comment]
It is not executing. The videos show all the steps I take as advised in the blog post.

**Comment by dstyvsky** [comment]
here are youtube links. should be better than .zip

https://youtu.be/IwLD5BFHzFo
https://youtu.be/YWuyII8fy_U


thanks for the assistance

really looks like a great tool

**Comment by slaeryan** [comment]
Thanks for the YouTube links, please hold on while I examine the issue.

**Comment by dstyvsky** [comment]
It is public now

**Comment by dstyvsky** [comment]
I updated the shellcode at: https://raw.githubusercontent.com/dstyvsky/TESTING/master/test2.txt

Without the output from the following command:
msfvenom -p  windows/x64/exec cmd=calc.exe -f hex > outfile2 

Executed on the 64 bit Windows 10 machine with x64 option set in FaclonStike with the same null result.

**Comment by dstyvsky** [comment]
Now this has also been tested on the 32 bit Windows 10 system pointing at your shellcode with the i686 option set as well. Still no result.

**Comment by slaeryan** [comment]
Hey mate,

A small bug has been identified in the checkDate() in safety_measures.cpp which is leading to us getting different results for the same shellcode.
It shall be fixed within 24 hours :)
Thank you for pointing it out!

**Comment by dstyvsky** [comment]
You're welcome!

**Comment by slaeryan** [comment]
Hey!

The issue with the killdate has been fixed now, please verify it.
Thank you again for pointing it out!

**Comment by dstyvsky** [comment]
Still no luck on 64 bit

![2](https://user-images.githubusercontent.com/13374252/81475695-c5c35680-91db-11ea-8966-93a250212429.png)
![3](https://user-images.githubusercontent.com/13374252/81475696-c65bed00-91db-11ea-92f6-b42962ca40e0.png)
![4](https://user-images.githubusercontent.com/13374252/81475697-c6f48380-91db-11ea-8e9f-6a4d4cb616c7.png)
![Untitled picture](https://user-images.githubusercontent.com/13374252/81475698-c78d1a00-91db-11ea-9fae-efe98f500734.png)

**Comment by dstyvsky** [comment]
And 32 bit as well:


![32_1](https://user-images.githubusercontent.com/13374252/81475779-5306ab00-91dc-11ea-9776-db2eb59d1414.png)
![32_2](https://user-images.githubusercontent.com/13374252/81475780-5437d800-91dc-11ea-85ef-888884025c94.png)



Update command that was run before any of this testing:

![update](https://user-images.githubusercontent.com/13374252/81475826-7d586880-91dc-11ea-90d1-e7103e7211e3.png)

**Comment by Sumalyo** [comment]
@dstyvsky I have tested the

**Comment by dstyvsky** [comment]
I included the hostname and killdate in my screenshots. Do I need to make another video?

**Comment by dstyvsky** [comment]
I renamed the system to 'desk' to simplify things and moved the date closer to what slaeryan used in his example. Still no dice.

![image](https://user-images.githubusercontent.com/13374252/81477686-f65cbd80-91e6-11ea-93a9-ca2f5aa456af.png)

**Comment by Sumalyo** [comment]
@dstyvsky As a proof of concept of deployment I have here replicated all your given details exactly on my machine (except hostname) and have successfully generated and tested the dropper 
as you can check out on this youtube video

[https://youtu.be/3KVvlIcC6oM](url)

![Screenshot from 2020-05-09 23-11-29](https://user-images.githubusercontent.com/39642083/81481851-8a16a400-9250-11ea-869e-2005bb9838c4.png)
And here I give the exact terminal ss during payload generation

Nevertheless taking full cognizance of the issues you have faced and duly apologizing for the same due to the bug in the checkDate() function I urge you to execute the executable at
[https://github.com/Sumalyo/gayetri/blob/master/toGive.exe](url) 

Which I have generated for your hostname "desk" for the calc.exe shellcode 
![Screenshot from 2020-05-09 23-19-31](https://user-images.githubusercontent.com/39642083/81481933-204aca00-9251-11ea-9d5c-8762697c2538.png)


This has been done with the most updated version of the repo and should work just fine. Please do record your due execution and upload it on YouTube if you face any issue this time, this would help us sincerely to review our code and make changes again if necessary


I may also take a chance here to convey a very important thing to you 
**The Shellcode you have uploaded is incorrect as it has an extra line ,line 2 appended to it **

**The Shellcode must be in a single line of code and must not contain any \x character in it**


Thanking You,
@Sumalyo

**Comment by dstyvsky** [comment]
Still no luck on 64 bit Windows 10 system. Did not try the 32.

I used the slaeryan shellcode. Thanks for the tip about the single line shellcode.

<img width="407" alt="64_bit_1" src="https://user-images.githubusercontent.com/13374252/82128715-1a8e4080-978b-11ea-9dc0-e510d9913c3e.PNG">
<img width="521" alt="64_bit_2" src="https://user-images.githubusercontent.com/13374252/82128716-1cf09a80-978b-11ea-8e70-262a027edb59.PNG">

**Comment by Sumalyo** [comment]
Yeah @dstyvsky the 64 bit version has an issue , we would fix it soon try the 32 bit version please

**Comment by dstyvsky** [comment]
<img width="456" alt="falcon1" src="https://user-images.githubusercontent.com/13374252/82479933-0c009b80-9aa1-11ea-8d11-36cd3f25d865.PNG">
<img width="507" alt="falcon2" src="https://user-images.githubusercontent.com/13374252/82479942-0e62f580-9aa1-11ea-9df0-5f228786c293.PNG">


I can record a video if need be but these screenshots should be sufficient. Let me know if I can provide further information that would be of use. 32 bit is failing as well. All steps taken and commands executed are documented in the screenshots. If the 64 bit is failing completely, should the issue be reopened? What seems to be the problem? Thanks for the assistance. This really does appear to be an interesting project.

**Comment by slaeryan** [comment]
Hey @dstyvsky,

I really have no clue as to why this doesn’t seem to work for you. The 32-bit variant works on every machine that I’ve tested in my lab. 
Here are some hints for debugging the code:
Go to the source dir and build a debug binary by uncommenting the print statements and whatever’s needed. Instructions on manual compilation is provided in the source. Figure out the step in which the error is occurring by strategically printing to the console. You could even attach a debugger and inspect.
Finally, you could try to create a fresh VM and try running it there. 
As for the 64-bit implant, you can open a separate issue for that. The problem seems to be in the Process Hollowing technique used in the injector.cpp file. Can’t get it to work with a 64-bit implant. I’ll debug it as soon as I have some time. By the way pull requests are more than welcome if you find the fix or maybe for some other cool feature you wanna add. 
Feel free to contact me if you need further assistance.

Regards,
@slaeryan.

**Comment by dstyvsky** [comment]
Thanks @slaeryan.

I may just have to take a look under the hood as you have suggested. These vm's are both pretty fresh. The 32 bit has only been used for this testing and was just stood up today.
